version: '3.2'
services:
  bot-ui:
    image: serhiyskoromets/cpd-bot-ui
    ports:
    - "8282:8282"
    network_mode: host
  bot-brain:
    image: serhiyskoromets/rasa-bot-core
    ports:
    - "5002:5002"
    network_mode: host
    depends_on:
    - bot-ui
    - duckling
  duckling:
    image: rasa/duckling
    ports:
    - "8000:8000"
    network_mode: host

