version: '3.2'
services:
  bot-ui:
    image: serhiyskoromets/cpd-bot-ui
    ports:
    - "8282:8282"
    network_mode: host
    depends_on:
    - mongo
  bot-brain:
    image: serhiyskoromets/rasa-bot-core
    ports:
    - "5002:5002"
    network_mode: host
    depends_on:
    - bot-ui
    - duckling
    volumes:
    - type: bind
      source: ./bot-brain/models/current/dialogue
      target: /app/models/current/dialogue
    - type: bind
      source: ./bot-brain/models/current/nlu
      target: /app/models/current/nlu
  duckling:
    image: rasa/duckling
    ports:
    - "8000:8000"
    network_mode: host
  mongo:
    image: mongo:latest
    ports:
    - "27017:27017"
    volumes:
    - '../cpd-mongo-db:/data/db'
    network_mode: host

